name: angry_bird_game_02
description: A simple Angry Birds style game using Flutter + Flame + Forge2D
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.15.0
  flame_forge2d: ^0.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
